name: Justimagine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.702909508952871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcb79a'
    - '#060805'
    - '#797762'
    - '#fafffb'
    - '#5f2c0d'
  brandStrength: 0.4375
  lightness: 0.9118823260068893
  saturation: 0.325423632748425
  rhythmicContrast: 0.37398457806557417
purpose: []
