typography_spectrum: 0.702909508952871
color:
  brandColors:
    - '#bcb79a'
    - '#060805'
    - '#797762'
    - '#fafffb'
    - '#5f2c0d'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.325423632748425
  rhythmicContrast: 0.37398457806557417
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Justimagine
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: A world of pure imagination
purpose: []
